### PR TITLE
tests/pup/sensors Add color_arguments.py and color_default.py

### PR DESCRIPTION
**Pull request by BertLindeman**
Add tests in pybricks-micropython [for issue pybricks-coverage 1](https://github.com/pybricks/pybricks-coverage/issues/1)
color_arguments.py: Verify that ambient() and reflection() refuse an argument 

color_default.py 
  Verifies color sensor arguments, by asserting that the same colors are reported by using the default argument, e.g. surface=True
  and using NO argument

### CODE REVIEW

**Comment by BertLindeman** [comment]
Please be critical so I can learn.

**Comment by BertLindeman** [comment]
Please help me . . . 

Where can I find the details of the error reported by the format check?
image

Pressing "Details"  just shows:
image

Or even.. I probably missed reading some doc about how to contribute

**Comment by dlech** [comment]
This is what I see when I click details:

image


Anyway, we use the code formatting script from MicroPython to automatically format code.

    poetry run python tools/codeformat.py

**Comment by BertLindeman** [comment]
Thanks @dlech 
Browser related: firefox does not show them, MS Edge **does**
codeformat sorted, Thank you!

**Comment by laurensvalk** [comment]
> Please be critical so I can learn.

:+1: Disclaimer: I may contradict myself a lot, and we tend to change the rules/standards from time to time. :smile: 

With that out of the way:
- We have some [recommendations](https://github.com/pybricks/pybricks-micropython/blob/master/CONTRIBUTING.md#commit-messages) for commit messages. For tests, see [these examples](https://github.com/pybricks/pybricks-micropython/commits/master/tests/pup/sensors/ultrasonic_distance.py).
- For small changes like new lines or formatting, you can usually amend your previous commit instead of making a new one. To do so, stage your new changes and do `git commit --amend`. This is not a hard requirement for now, since we can do it for you when we merge your PR, but it's nice for the future.
- Have a look at the `Description:` of the other tests. There is no special spacing.
- Please format comments as sentences, including a period.
- Consider Python standards for variable names. E.g. `ambientD` could be replaced by `ambient_d`. I don't know what `D` stands for, so writing the whole thing might be even better (`ambient_something`).

The tests themselves are short and to the point, which is nice. Over time, I guess we will try to find the right balance for things to test per script. For example, checking all argument variations and default settings might all go well together in a single script.

**Comment by BertLindeman** [comment]
Thanks @laurensvalk 

> Disclaimer: I may contradict myself a lot, and we tend to change the rules/standards from time to time

Let's call it progressive insights. 😃 

> For example, checking all argument variations and default settings might all go well together in a single script.

Do you mean more like the first PR I made in "coverage"? Hihi. Just joking!

But more seriously, that test, but more like these two tests?
So without output if all OKE and with asserts?

Will look at your points above and make the tests and the PR better, as a start.
python variable naming is a bit of a blur to me.
They should be short but clear about what they stand for.

I am using the Github website to build the PR for the tests as I am still a nitwit in git.

Would it be better to delete this PR and start over? 
There is not a lot of work in there.

**Comment by laurensvalk** [comment]
> Would it be better to delete this PR and start over?

No, please keep this PR. It's just two clicks for us to squash them into just 1 commit, so don't worry about that aspect.

> Do you mean more like [...]

Not sure yet. I'm writing a few motor tests now to find out what I think :smile:

**Comment by BertLindeman** [comment]
> No, please keep this PR. It's just two clicks for us to squash them into just 1 commit, so don't worry about that aspect.
> 
> > Do you mean more like [...]
> 
> Not sure yet. I'm writing a few motor tests now to find out what I think 😄

Thank you, Laurens. Looking forward to these new tests.

**Comment by laurensvalk** [comment]
> Looking forward to these new tests.

See https://github.com/pybricks/pybricks-micropython/commit/6dcd935b7b4d5dc85ae133ee0b36e76344c2ceae

**Comment by BertLindeman** [comment]
> > Looking forward to these new tests.
> 
> See [6dcd935](https://github.com/pybricks/pybricks-micropython/commit/6dcd935b7b4d5dc85ae133ee0b36e76344c2ceae)

Good examples.

Should you update the copyright year?

**Comment by laurensvalk** [comment]
> Should you update the copyright year?

Good catch! Will do.

**Comment by laurensvalk** [comment]
Another thing you'll notice is that I started doing things like:

```python
# Test reset to absolute value, given that sensor sees object at the top.
motor.reset_angle()
assert -5 <= motor.angle() <= 5, "Unexpected absolute motor angle."
```

Instead of an elaborate expression with an `expected_value`, `measured_value`, and `format(...)` as I did in some older tests. This is to keep things simpler. When a test fails, we'll probably have to dig into the test anyway.

**Comment by laurensvalk** [comment]
Thanks! Merged as-is for now.

**Comment by BertLindeman** [comment]
@laurensvalk thank YOU!

**Pull request merged**
