### PR TITLE
Change to default main.py

### PR DESCRIPTION
**Pull request by GianCann**
This code work with every Powered Up Hubs

### CODE REVIEW

**Comment by dlech** [comment]
Thanks!

Be sure to run `./tools/codeformat.py` to fix the formatting problems.

**Comment by laurensvalk** [comment]
Also be sure to check the recommendations for commit messages :)

We will probably be working on the hub UI quite soon and then take a look at the main scripts as well.

**Comment by GianCann** [comment]
Yes, ok,

**Comment by laurensvalk** [comment]
Updated and merged, thanks! You're a Pybricks contributor now :tada:

**Pull request merged**
